info:
  description: Spring Cloud Samples
  url: https://github.com/yucea/learning
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
message: Spring Cloud Config Server!!